name: Update assignees

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  update-assignees:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.repository_owner == 'monarchmoney' }}
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
